### PR TITLE
Updates for Jekyll 3

### LINKED ISSUE #8: page build warning - pygments highlighter
On pressing the merge button for #7 I received this email.   Sounds minor but didn't want to just drop it on the floor.

```
The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

### PR DESCRIPTION
**Pull request by grondo**
Some updates and cleanup for Jekyll 3.x with a proper switch to the rouge highlighter.

Since we're not using pygments, the unwieldy `{% highlight bash %}` code block syntax was removed and replaced with GFM style backticks.

The pygments highlighter style sheet is also replaced with one generated from `rougify style base16.dark`

Fixes #8

### CODE REVIEW

**Comment by grondo** [comment]
ping?

**Comment by garlick** [comment]
How is this being checked to make sure it has the desired effect?  Is there some way to preview online or must one set up the Jekyll environment locally to do that?

Sorry for being clueless.

**Comment by grondo** [comment]
Sorry, I don't know a way to run any kind of integration test on a website.

The easiest way to check out the changes would be to use a c9.io instance.

Install the github-pages gem

```
$ gem install github-pages
```

Then, in the top level directory of your working copy, run the appropriate jekyll command to build and serve the site:

```
$ jekyll serve -H $IP -P $PORT
```

The c9.io window will pop up a link to which you can browse to view the site.

**Comment by garlick** [comment]
That worked.  Thanks!!!  And it's pretty cool!  Also, sorry I know you told me about that before.

Its useful to be able to at least give web site changes a sanity check, and I think I've done that, so merging.

**Pull request merged**
