### PR TITLE
flux-framework site update, and addition of quickstart content

### PR DESCRIPTION
**Pull request by grondo**
This *experimental* PR includes a complete update of the flux-framework GitHub organization pages. A new basic theme is introduced (borrowed heavily from jekyllrb.com site) which allows posts, news, and docs to be supported, with sidebar navigation for news and docs.

Previewing the site on my personal fork didn't seem to work, so I currently have it running [here](https://flux-pages-grondo.c9users.io/). Excuse the tacky landing page marketing speak and cheesy logo.

The basic way the site would work now is:

 * docs are dropped into `_docs/*.md` with a line added to `_data/docs.yml` from which the docs navigation sidebar is built
 * posts and news items are dropped into _posts/YYYY-MM-DD-post-slug.md with front matter tags as in the example:
 ```
---
layout: news_item
title: "Test post"
date: "2015-11-24 10:46:20 -08:00"
author: grondo
categories: info
---
 ```

Currently, Docs are thin, but I did add a Quickstart (for flux-core).

### CODE REVIEW

**Comment by lipari** [comment]
Very nice, @grondo !  I actually *like* the cheesy logo.

**Comment by grondo** [comment]
Ok, I made some small updates and pushed the result. Notably the `README.md` now has basic instructions for adding new news and docs items to the site.

**Comment by garlick** [comment]
This looks really great @grondo!  It even renders decently on my phone.  The high level docs you've added ought to get the point of the project across to people who've wandered here.

Would it make sense to merge this now and do any further development in other PR's?  The next low hanging fruit might be getting our RFC, man(1), and man(3) content up?

How did you make flux-pages-grondo.c9.io work?

**Comment by grondo** [comment]
Yeah, unfortunately I don't see a good way to test whether the site will work under GitHub pages until we actually merge the PR. It is probably ok to merge now and then fix up the eventual problems in future PRs. (sorry if it completely doesn't work at all)

I was thinking that flux-framework.github.io could perhaps stay a high-level site with HOWTOs and generic information (it does seem to make sense for RFCs to go here as well), but command and API documentation could perhaps live in the project pages? This way we could (eventually) look into auto-generated docs (from asciidoc pages) into a static site, pushed to each project's `gh-pages` branch?

In fact, we might be able to get going quickly with something like [flatdoc](https://github.com/rstacruz/flatdoc), though I haven't looked deeply into it (and it supports markdown not asciidoc)

For flux-pages-grondo.c9.io, I am just running `jekyll serve` by hand against my working copy in a public c9.io instance. cloud9 is nice enough to provide public IPs for just this purpose (though it is completely open so probably don't want to be running in this mode for too long)

**Comment by garlick** [comment]
OK, let's merge then and see where we are.

**Comment by grondo** [comment]
Thanks! Looks like most things are in order, but the "Improve this page" links on docs are broken.

**Comment by garlick** [comment]
Yeah looks great.  I like the logo too!

I think you're right about keeping the content general - RFC's but not manual pages.

**Pull request merged**
