### PR TITLE
posts: generate latest release notes

### PR DESCRIPTION
**Pull request by chu11**
Problem: The releases list was crazy out of date.

Solution: update it!

### CODE REVIEW

**Comment by chu11** [comment]
oh, i just noticed #52, I added flux-security release too

**Review by cmoussa1 — APPROVED** [review]
LGTM! Thanks for putting this together @chu11

**Comment by chu11** [comment]
@cmoussa1 i guess we don't have mergifyio on this repo, so i guess you need to push the button

**Comment by cmoussa1** [comment]
Sounds good, I'll hit merge then!

**Pull request merged**
